name: Update documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc]
      - name: Build with Sphinx
        run: cd doc && make html
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: ./doc/_build/html
  upload:
    name: Upload to GitHub pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download documentation artifact
        uses: actions/download-artifact@v2
        with:
          name: documentation
          path: ./html
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
