name: Check pull request

on:
  pull_request:

jobs:
  unittest:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyopengl==3.1.6
        pip install .[test]
    - name: Test with pytest
      run: |
        pytest ./test/
  upload:
    name: Upload coverage report
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyopengl==3.1.6
          pip install .[test]
      - name: Produce coverage report
        run: |
          pytest --cov dm_robotics.panda --cov-report xml:coverage.xml ./test/
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  linting:
    name: Linting with pylint
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[lint]
      - name: Run pylint
        run: pylint --rcfile .pylintrc src/
